version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  cheklinim-my-netology-hw:
        name: cheklinim-my-netology-hw
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1

services:

  cheklinim-netology-prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cheklinim-netology-pushgateway:cheklinim-netology-pushgateway
    depends_on:
      - cheklinim-netology-pushgateway
    networks:
      - cheklinim-my-netology-hw
    restart: always
#    deploy:
#      placement:
#        constraints:
#          - node.hostname == ${HOSTNAME}

  
  grafana:
    image: grafana/grafana
#    user: "472"
    depends_on:
      - cheklinim-netology-prometheus
    ports:
      - 80:3000
    volumes:
      - grafana_data:/var/lib/grafana
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./custom.ini:/etc/grafana/grafana.ini
#    env_file:
#      - ./grafana/config.monitoring
    networks:
      - cheklinim-my-netology-hw
    restart: always

  cheklinim-netology-pushgateway:
    image: prom/pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - cheklinim-my-netology-hw
