version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
    cheklinim-my-netology-hw:
        driver: bridge
        ipam:
          config:
            - subnet: 10.5.0.0/16
              gateway: 10.5.0.1


services:

  cheklinim-netology-prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    links:
      - cheklinim-netology-pushgateway:cheklinim-netology-pushgateway
    depends_on:
      - cheklinim-netology-pushgateway
    networks:
      - cheklinim-my-netology-hw
    restart: always
  

  cheklinim-netology-pushgateway:
    image: prom/pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - cheklinim-my-netology-hw
  
  grafana:
    image: grafana/grafana
    depends_on:
      - cheklinim-netology-prometheus
    ports:
      - 80:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/grafana.ini
    networks:
      - cheklinim-my-netology-hw
    restart: always
